#
# LoRa mail notififer.
#

language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - pio lib install 374 1006

script:
    - platformio run

